### ISSUE TITLE
ArtifactResolutionException: Could not find artifact org.clojure:clojure:jar:1.7.0

### ISSUE THREAD

**Issue by aviflax** [taylorwood/clj.native-image#2] opened 2018-10-18 16:26 UTC
<details>
<summary><b>Command and full output from my shell</b></summary>

```
$ clojure -A:native-image
Loading fc4.cli.wcb
Compiling fc4.cli.wcb
Exception in thread "main" org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.clojure:clojure:jar:1.7.0
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:260)
	at clojure.tools.deps.alpha.extensions.maven$get_artifact.invokeStatic(maven.clj:95)
	at clojure.tools.deps.alpha.extensions.maven$get_artifact.invoke(maven.clj:91)
	at clojure.tools.deps.alpha.extensions.maven$eval395$fn__397.invoke(maven.clj:112)
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)
	at clojure.tools.deps.alpha$lib_paths$fn__765.invoke(alpha.clj:203)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__7839.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6748)
	at clojure.core$reduce.invoke(core.clj:6730)
	at clojure.tools.deps.alpha$lib_paths.invokeStatic(alpha.clj:199)
	at clojure.tools.deps.alpha$lib_paths.invoke(alpha.clj:197)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:229)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:210)
	at clj.native_image$deps__GT_classpath.invokeStatic(native_image.clj:12)
	at clj.native_image$deps__GT_classpath.invoke(native_image.clj:9)
	at clj.native_image$_main.invokeStatic(native_image.clj:61)
	at clj.native_image$_main.doInvoke(native_image.clj:43)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.clojure:clojure:jar:1.7.0
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:412)
	... 32 more
```
</details>

<details>
<summary><b>My <code>deps.edn</code></b></summary>

```edn
{:paths ["src/main" "src/cli"]
 :deps
 {org.clojure/core.async      {:mvn/version "0.4.474"}
  org.clojure/spec.alpha      {:mvn/version "0.2.168"}
  org.clojure/tools.cli       {:mvn/version "0.3.7"}
  circleci/clj-yaml           {:mvn/version "0.5.6"}
  potemkin                    {:mvn/version "0.4.5"}
  expound                     {:mvn/version "0.7.1"}
  com.cognitect/anomalies     {:mvn/version "0.1.12"}
  ;; test.chuck is in the main dependency list, rather than in the test profile,
  ;; because we’re using one of its generators in a spec in a source file.
  ;; This means we’ll also need org.clojure/test.check at runtime. Not ideal,
  ;; but worth it.
  com.gfredericks/test.chuck  {:mvn/version "0.2.9"}}

 :aliases {:dev       {:extra-deps  {org.clojure/tools.trace    {:mvn/version "0.7.9"}
                                     inspectable                {:mvn/version "0.2.2"}}}

           :test      {:extra-paths ["test" "src/test_utils"]
                       :extra-deps  {org.clojure/test.check     {:mvn/version "0.10.0-alpha3"}
                                     eftest                     {:mvn/version "0.5.3"}}}

           :test/run  {:main-opts   ["-m" "fc4.test-runner.runner"]}

           :test/coverage
                      {:extra-deps  {cloverage                  {:mvn/version "1.0.13"}}
                       :main-opts   ["-m" "cloverage.coverage"
                                     "--src-ns-path" "src/main"
                                     "--test-ns-path" "test"
                                     "--runner" ":fc4.test-runner"
                                     "--fail-threshold" "65"
                                     "--codecov"]}

           :lint      {:extra-deps  {github-JamesLaverack/cljfmt-runner
                                     {:git/url "https://github.com/JamesLaverack/cljfmt-runner"
                                      :sha     "51f85c9d6cc67107620749ceacd46120647fe107"}}
                       :main-opts   ["-m" "cljfmt-runner.check"]}

           :lint/fix  {:main-opts   ["-m" "cljfmt-runner.fix"]}

           :native-image
                      {:main-opts   ["-m clj.native-image fc4.cli.wcb"
                                     "-H:Name=wcb"]
                       :extra-deps  {clj.native-image
                                     {:git/url "https://github.com/taylorwood/clj.native-image.git"
                                      :sha "0f113d46f9f0d07e8a29545c636431ddf5360a7d"}}}

           :clj-next  {:override-deps {org.clojure/clojure {:mvn/version "1.10.0-alpha6"}}}}

 :jvm-opts ["-Dclojure.compiler.direct-linking=true"]}
```

</details>

<details>
<summary><b>My System</b></summary>

I’m using this software:

* MacOS: 10.13.6
* JDK: 1.8.0_171-b11
* Clojure: stable 1.9.0.397, installed via Homebrew today
* GraalVM Community Edition 1.0 RC7, downloaded today and manually “installed” under `/usr/local/`

</details>

<br>

If you’d like to try to reproduce in the context of my project, you can check out [this branch](https://github.com/FundingCircle/fc4-framework/tree/graal).

I’d appreciate any assistance! Thank you!

**Comment by taylorwood** [comment] 2018-10-19 04:12
Thanks for the detailed issue, I was able to reproduce it. I think there's a bug where the install- and user-level deps.edn files aren't considered, but I was able to workaround it by supplying the default Maven repo URLs and Clojure 1.9 dependency from install-level deps.edn:
```clojure
 :deps {org.clojure/clojure {:mvn/version "1.9.0"}}
 ...
 :mvn/repos
 {"central" {:url "https://repo1.maven.org/maven2/"}
  "clojars" {:url "https://clojars.org/repo"}}
```

Another issue is the project entry point, which needs `(:gen-class)` added to the namespace declaration of `fc4.cli.wcb`, and `(set! *warn-on-reflection* true)` is a good idea too. `native-image` may also suggest `--report-unsupported-elements-at-runtime` and `--delay-class-initialization-to-runtime=<class-name>` for other issues.

But ultimately I run into what may be an issue with some usages of Clojure 1.9 as reported here https://github.com/oracle/graal/issues/612, which might be addressed in this branch https://github.com/clojure/clojure/compare/master...ghadishayban:graal-test#diff-d951a5cd799ae841ffcc6b45598180dbR1648. There's another GraalVM-specific fix in Clojure 1.10 beta, but that `locking` macro tweak isn't merged AFAIK.

Compiling a non-trivial project like this with `native-image` can be difficult (or impossible) at the moment (e.g. I haven't been able to get clojure.spec working) but regular progress is being made. FWIW I have some example projects [here](https://github.com/taylorwood/lein-native-image/tree/master/examples) and [here](https://github.com/taylorwood/clojurl) — some with fairly complex dependencies like http-kit, StanfordNLP, reflection workarounds, etc.

**Closed as completed** 2018-10-21 02:13 UTC
Labels: bug

**Comment by aviflax** [comment] 2018-10-22 16:38
@taylorwood thank you so much for the investigation, explanation, the improvement to the tool, and all the super-helpful information! I really appreciate it!

**Comment by ghost** [comment] 2018-11-20 02:11
> I haven't been able to get clojure.spec working

@taylorwood any possible clue about this? 

PS thx for making this tool

**Comment by taylorwood** [comment] 2018-11-20 09:23
@yiwan I can't recall why I couldn't get clojure.spec working before — may have been due to an issue in GraalVM CE 1.0.0-RC7 at the time — but I'm able to use it now with GraalVM CE 1.0.0-RC9. See https://github.com/taylorwood/clojurl/commit/530a5a9b8b37b2405e5c36ef8d47776b1b75c86c for a working example.

Thanks for the reminder to try the latest RC build (and get better results)!
