### ISSUE TITLE
Compile path doesn't include :extra-paths from aliases

### ISSUE THREAD

**Issue by jmmk** [taylorwood/clj.native-image#14] opened 2019-09-28 23:40 UTC
In my `deps.edn`, I have the following setup:

```clojure
{:paths []
 :aliases {:clj {:extra-paths ["src/clj"]}
                 :native-image {:main-opts ["-m clj.native-image namespace.core"]}}}
```

And my main namespace is in `src/clj/namespace/core.clj`.

When trying to build with `clj -A:clj:native-image` I get:
> Error: Main entry point class 'namespace.core' not found.

---

It seems that `:extra-paths` from active aliases are not taken into account when finding files to compile.

**Comment by jmmk** [comment] 2019-09-29 20:34
As far as I can tell there's no way to access the `aliases` outside of the `clojure` shell script (it doesn't pass those args on to any "main" script running), so it doesn't seem like you can pull the `:extra-paths` out explicitly for the `find-namespaces-in-dir` check.

It seems like you would have to either:

- look for all namespaces on the classpath, which is extreme
- Have the source paths passed as an argument to `clj.native-image` which could be annoying since they are already defined in `deps.edn` and may change as the `:extra-paths` change.

---

I have a question though: Could you just call `compile` on the `main-ns` arg? If `deps.edn` is configured properly, it (and all deps) should be on the classpath and any source dependencies will also be compiled. Since the `main-ns` is what's being passed to Graal, wouldn't this compile everything that's needed?

I am not familiar with Clojure compilation, so I may be missing something

**Comment by jmmk** [comment] 2019-09-29 21:23
I changed

```clojure
(let [deps-map (merged-deps)
      namespaces (mapcat (comp find-namespaces-in-dir io/file) (:paths deps-map))]
      (prep-compile-path)
      (doseq [ns namespaces]
        (println "Compiling" ns)
        (compile (symbol ns)))
```

to

```clojure
(prep-compile-path)
(compile (symbol main-ns))
```

and it worked in my project, but it's very minimal so I don't know if there's anything more complex that could change the compilation requirements

**Comment by taylorwood** [comment] 2019-09-29 22:32
> Could you just call compile on the main-ns arg?

Yes, this is how it worked previously — the idea being that anything that needed AOT compilation would be `require`d by the main namespace and be transitively compiled when that namespace compiles: https://github.com/taylorwood/clj.native-image/commit/567176ddb0f7507c8b0969e0a10f60f848afaf7d#diff-cacd55da9eaa0edb5d79e1e82917ed9dL74-L76 I can't recall exactly what prompted this change but I think it was to address an issue for projects where all namespace aren't `require`d from the main namespace.

I'm curious why the source is specified in `:extra-paths` and `:paths` is empty in your example deps.edn. By default, deps.edn assumes the source will be in `src` directory of project. Even so, there may be a very simple fix to make it work for you:
```clojure
(let [deps-map (merged-deps)
      namespaces (->> (concat (:paths deps-map) (:extra-paths deps-map))
                      (mapcat (comp find-namespaces-in-dir io/file)))]
```
`:extra-paths` wasn't being searched for namespaces. Let me know if you can verify this change with your project, otherwise I'll try to reproduce it soon. Thanks for the detailed report!

**Comment by jmmk** [comment] 2019-09-30 02:23
> I think it was to address an issue for projects where all namespace aren't required from the main namespace.

If not everything was `require`d, wouldn't`native-image` also fail to include it? If you could simply `compile` the main namespace rather than having to compile all namespaces in all configured paths it would simplify this a lot

> I'm curious why the source is specified in :extra-paths and :paths is empty in your example deps.edn.

This is my first time setting up a project with `deps.edn` so I'm probably doing something non-standard. I did whatever kept `clj` and `cljs` separate (source + deps) and worked with Cursive and the cli tools (like `shadow-cljs`)

> namespaces (->> (concat (:paths deps-map) (:extra-paths deps-map))
                      (mapcat (comp find-namespaces-in-dir io/file)))

This doesn't work as written: `deps-map` here is the merged deps.edn and doesn't have `:extra-paths` at the top level. It would require pulling `:extra-paths` from all aliases.

It could also potentially result in extra work (compiling things from inactive aliases)

---

Here's my opinion:

The best solution is `(compile (symbol main-ns))` unless there's a known case that fails to compile properly with `native-image`

Beyond that, I think supporting the standard configuration (`:paths` or `"src"`) out of the box makes sense. For non-standard configurations (like mine), make the caller do more work (e.g. allow passing a list of extra paths or aliases)

**Comment by taylorwood** [comment] 2019-09-30 04:38
>If not everything was required, wouldn't native-image also fail to include it?

Not necessarily. You can also compile shared libraries with native-image (with `--shared` flag), where you may want to vendor code/classes that aren't directly referenced in the project itself.

> rather than having to compile all namespaces in all configured paths it would simplify this a lot
> [...] unless there's a known case that fails to compile properly with native-image

Agreed, and I wish I'd better documented this change from the original behavior. I'm almost certain it was due to an issue compiling another project but I don't have time at the moment to dig into it.

So I think the low risk, quick fix is to simply ensure `main-ns` is compiled. I made a minimal repro case and tested this change with it and a few other projects. Please let me know if the latest commit works for you:
https://github.com/taylorwood/clj.native-image/blob/6733181a7b01768e0b3b01df3ee7780fd1236fae/src/clj/native_image.clj#L83

**Comment by jmmk** [comment] 2019-09-30 14:18
`(doseq [ns (distinct (conj namespaces main-ns))]`

That's a fair solution. I tested and it does solve my issue. 

I added the source directory to `:paths` as a test and it does generate some duplicate `.class` files, but the compilation time is not increased (not doing much/any extra work) and the resulting executable produced by `native-image` seems the same size

**Closed as completed** 2019-09-30 14:23 UTC
Labels: bug
